library(tidyverse)
library(timetk)

rm(list = ls())

tidyNottem <- function(temperatures) {
  tk_tbl(temperatures) %>% 
    separate(col = index,
             into = c("month","year"),
             sep = " ") # index automatically generated by tk_tbl()
}

nottem %>% 
  tidyNottem()