library(tidyverse)
library(timetk)

# remove previous objects in global environment
rm(list = ls())

# functions
tidyNottem <- function(temperatures) {
  tk_tbl(temperatures) %>% 
    separate(col = index, # index automatically generated by tk_tbl()
             into = c("month","year"),
             sep = " ") 
}

addCelsiusColumn <- function(temperatures) {
  temperatures %>% 
    mutate(celsius = (value - 32) * 5/9) %>% 
    rename(fahrenheit = value)
}

summariseAvgTemperatureByYear <- function(temperatures) {
  temperatures %>% 
    group_by(year) %>% 
    summarise(avgTemperature = mean(celsius))
}

plotAvgTemperaturesByYear <- function(avg_temperatures) {
  ggplot(data = avg_temperatures,
         aes(x = year, y = avgTemperature)) +
    geom_line(group = 1) +
    labs(title = "average temperature by year in Nottingham (1920-1939)",
         y = "average temperature")
}

calculateAutoCorrelation <- function(avg_temperatures) {
  acf(avg_temperatures$avgTemperature, lag.max = 1, plot = FALSE)$acf[2]
}


# main analysis
temperatures <- nottem %>% 
  tidyNottem() %>% 
  addCelsiusColumn

avg_temperatures_by_year <- temperatures %>% 
  summariseAvgTemperatureByYear()

plotAvgTemperaturesByYear(avg_temperatures_by_year)
calculateAutoCorrelation(avg_temperatures_by_year)

ggsave(filename = "avg_temperatures_by_year.png")

